# Project-wide Gradle settings.
android.useAndroidX=true
android.enableAppCompileTimeRClass=true

org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

APP_VERSION_CODE=6991
APP_VERSION_NAME=12.9.2
APP_PACKAGE=com.nasigram.app
TG_APP_VERSION_CODE=6991
TG_APP_VERSION_NAME=12.9.2
